### GET

GET http://localhost:5000/api/v1/dropdown

### PUT

PUT http://127.0.0.1:5000/api/v1/dropdown
Content-Type: application/json

{
    "old": {
        "_id": "5d45b71599752dd7ea7bb2ed"
    },
    "new": {
        "question_code": "for x in range(6):\n\tif x @@ 5: \n\t\tprint(x)"
    }
}

### POST

POST http://localhost:5000/api/v1/dropdown
Content-Type: application/json
Authorization: token bananas

{
    "tags": ["operators", "logic"],
    "difficulty": 1,
    "question_text": "What would make var True?",
    "question_code": "var = @@",
    "question_answer": "1==1",
    "alternatives": ["1==1", "2==1", "2!=2", "3==1"]
}

### POST 2

POST http://127.0.0.1:5000/api/v1/dropdown
Content-Type: application/json
Authorization: token bananas

{
    "tags": ["operators", "loops", "if"],
    "difficulty": 2,
    "question_text": "What would make this print 5?",
    "question_code": "for x in range(6):\n\tif x @@ 5: \n\t\tprint(x)",
    "question_answer": "==",
    "alternatives": ["<=", "<", ">", "=="]
}

### 

DELETE http://127.0.0.1:5000/api/v1/dropdown/5d57ea029f443260627e1772
Authorization: token bananas

### GET SET
GET http://localhost:5000/api/v1/dropdown/set/2

