### GET

GET http://127.0.0.1:5000/api/v1/dropdown

### PUT

PUT http://127.0.0.1:5000/api/v1/dropdown
Content-Type: application/json

{
    "old": {
        "_id": "5d45b71599752dd7ea7bb2ed"
    },
    "new": {
        "question_code": "for x in range(6):\n\tif x @@ 5: print(x)"
    }
}

### POST

POST http://127.0.0.1:5000/api/v1/dropdown
Content-Type: application/json

{
    "tags": ["operators", "logic"],
    "difficulty": 1,
    "question_text": "What would make this True?",
    "question_code": "result = 6 > 5 @@ (4 < 4 or 2 == 3 )",
    "question_answer": "or",
    "alternatives": ["and", "or", "==", "<="]
}

### POST 2

POST http://127.0.0.1:5000/api/v1/dropdown
Content-Type: application/json

{
    "tags": ["operators", "loops", "if"],
    "difficulty": 2,
    "question_text": "What would make this print 5?",
    "question_code": "for x in range(6):\n\tif x @@ 5: print(x)",
    "question_answer": ">=",
    "alternatives": [">=", "<=", "<", ">", "=="]
}

### 

DELETE http://127.0.0.1:5000/api/v1/dropdown/5d4415f621c23ded5805fa4b

### GET SET
GET http://localhost:5000/api/v1/dropdown/set/2

