### GET

GET http://127.0.0.1:5000/api/v1/multi_choice

### PUT

PUT http://127.0.0.1:5000/api/v1/multi_choice
Content-Type: application/json
Authorization: token bananas

{
    "old": {
        "_id": "5d57ebda656fba97852f8d1c"
    },
    "new": {
        "question_code": " for x in [1, 2, 3]: \n\tprint(x, end='')"
    }
}

### POST

POST http://127.0.0.1:5000/api/v1/multi_choice
Content-Type: application/json
Authorization: token bananas

{
    "tags": ["dicts"],
    "difficulty": 4,
    "question_text": "What does this print??",
    "question_code": "print({ True: 1, 1: 3, 1.0: 2 })",
    "question_answer": "{True: 2}",
    "alternatives": ["{True: 2}", "{ True: 1, 1: 3, 1.0: 2 }", "{True: 1}", "{1.0: 2}"]
}

### POST 2

POST http://127.0.0.1:5000/api/v1/multi_choice
Content-Type: application/json
Authorization: token bananas

{
    "tags": ["lists","loops"],
    "difficulty": 1,
    "question_text": "What does this print?",
    "question_code": " for x in [1, 2, 3]: \n\tprint(x, end='')",
    "question_answer": "123",
    "alternatives": [
        "1 2 3 4",
        "1, 2, 3",
        "1\n2\n3",
        "123"
    ]
}

###

DELETE http://127.0.0.1:5000/api/v1/multi_choice/5d57ea1e9f443260627e1773
Authorization: token bananas

### GET SET
GET http://localhost:5000/api/v1/multi_choice/set/2